### ISSUE TITLE
Filtering assets by tags and tagging multiple assets manually.

### ISSUE THREAD

**Issue by OctagonalHexy** [Gorgious56/asset_browser_utilities#107]
I'm currently working on some modular level kits for creating game levels and have need for multiple collections with overlapping assets for ease of access during level design.
Given that catalogues have A nested structure that makes this specific use case difficult. I turned to tags to immediately discover that they are barely implemented in default blender, which is how I found this project.

After using this addon to set tags for a short while I've come up with two improvements that I believe would make them much faster when searching for assets by tags and when tagging assets manually.

The first is keeping A list of every tag on any asset within the catalogue you have selected and making A panel beneath the catalogues menu that can be used to filter your currently selected catalogue to only the tags you have selected. Perhaps switching by default but allowing multiple to be selected while holding a key like control.

The second is an option in the 'assets context menu', when clicking this option another popup list appears with the same list of every tag in the selected catalogue allowing you to easily tag A manually selected group of assets with an existing tag.

![marked_screenshot](https://user-images.githubusercontent.com/85406370/199451770-995bd51c-7609-48c0-ab85-44c59611e183.png)

Thanks for reading my feature suggestion!

**Comment by Gorgious56** [comment]
Hello ! First of all thank you for your constructive feedback, I really appreciate it.

These are nice features ! Just as a bit of explanation, the main goal of this addon is not to provide new features but to automate the boring repetitive tasks that are already possible to do in the current system. I, too have some ideas for improving the asset browser. I feel like they ought to be implemented natively at some point, so I have chosen not to spend time on adding new features (custom rendering scenes, filters, import/export, etc.), or at least not features that I feel like will be there in the future (however far in time it may be :/ )

The tag system is in its infancy as you noticed, so is the whole asset browser editor. I feel like adding the list you are suggesting is providing a solution for a problem that should be solved in another way. I think that catalogs should work like collections in Blender, and that one asset may be part of several different catalogs. I don't really see the point of this design choice TBH.

For now you may look for a specific tag with the search filter 
![image](https://user-images.githubusercontent.com/25156105/199503483-27c01405-51d2-4119-a72e-8b8b1818b457.png)
that has also a lot of room for improvement, but I think what you are looking for will be provided by this feature. (when ? TBD) You can't look for more than 1 tag for example; You can't even specify you're looking for a tag. I think at some point we'll have something similar to the spreadsheet editor filter system (which is very new and improvable too)
![image](https://user-images.githubusercontent.com/25156105/199505118-45fb3738-6eec-48e3-9d22-7262e30e11d8.png)

The second thing you're looking for would be a nice addition but I don't want to clutter the interface too much with features that are already there. Here's for example how you can add kinda what you are looking for in your quick favorites :

![Animation2](https://user-images.githubusercontent.com/25156105/199504565-696867bc-38f3-4801-8c81-bf2b2c146bc1.gif)

I hope you understand my point, and I'll gladly keep  your suggestion around in case I change my mind. 

Cheers :)

**Comment by OctagonalHexy** [comment]
I think I understand.
Tags are not usable at the moment and there is no plan to change that.
I am disappointed but if that is not what this addon is for, than so be it.
Its frustrating that there is no way to make use of the tags I have set and I will keep looking to see if I can find A solution elsewhere.
Thanks.
