### ISSUE TITLE
Won't install with B3.4.1 portable (for me)

### ISSUE THREAD

**Issue by zerodean** [Gorgious56/asset_browser_utilities#116]
I have Blender 3.4.1 portable installed (and also use a custom directory for my addons -- however, I also installed to the regular addon directory and get the same issue). The addon shows up after install (using both zip install option as well as simply extracting zip to addon directory), but after restarting blender, I get this error when I try to activate it:

Traceback (most recent call last):
  File "X:\! BLENDER\blender-3.4.1\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "X:\! BLENDER\! ADDONS\addons\asset_browser_utilities-master\__init__.py", line 19, in <module>
    from asset_browser_utilities.core.cache.prop import Cache
ModuleNotFoundError: No module named 'asset_browser_utilities'

**Comment by 3DonkeyKings** [comment]
You have to remove the -master , then it will work

**Comment by zerodean** [comment]
Perfect! That works! Thank you. First time I've run into that issue, but it makes sense. Thanks for the quick response and your contributions to the blender community. Looking forward to testing this out.

**Comment by hannibalcheu** [comment]
where do we remove the -master?

**Comment by 3DonkeyKings** [comment]
If you download the .zip file from the main site through the green code button, then you have to unzip that und remove -master from the folder name.
You can then just move that folder to your addons folder and enable it in blender without installation.

If your downloading through the releases site then you can just install that .zip like a regular addon

**Comment by Gorgious56** [comment]
Hehe awesome thanks @3DonkeyKings for helping out ! Much appreciated

**Comment by hannibalcheu** [comment]
Thanks so much!  got working now.

**Comment by 3DonkeyKings** [comment]
Haha your welcome, both of you 😉

**Comment by Gorgious56** [comment]
Closing since this seems resolved, + we already have a troubleshoot issue for this https://github.com/Gorgious56/asset_browser_utilities/issues/35
