### ISSUE TITLE
Option to batch fill the License field.

### ISSUE THREAD

**Issue by mod3dx** [Gorgious56/asset_browser_utilities#123]
Hi!
 Is it possible to include this feature in the add-on?
![Screenshot_20230719_010238](https://github.com/Gorgious56/asset_browser_utilities/assets/104971293/be016657-3ab1-49b9-8557-2543c57adbaa)

**Comment by Gorgious56** [comment]
Done ! Thanks for the suggestion. The feature should be available if you download the latest live build.  Cheers

**Comment by Gorgious56** [comment]
Done ! Thanks for the suggestion. The feature should be available if you download the latest live build.  Cheers

**Comment by Gorgious56** [comment]
IF you have trouble running the live build please refer to https://github.com/Gorgious56/asset_browser_utilities/issues/35
