### ISSUE TITLE
Rename Collection Asset to Blend Name operation crashing Blender

### ISSUE THREAD

**Issue by rndllcprn** [Gorgious56/asset_browser_utilities#128]
I'm trying to mark assets using the collection filter and added a Custom Operation to rename the asset using the blend name. 
![image](https://github.com/Gorgious56/asset_browser_utilities/assets/68812484/366a201d-28ab-4ffb-8c58-dff7dae8b7c3)

I've tried multiple versions from 3.3 to 3.6 and all results in Blender closing and not leaving any crash logs.

This is the final messages from the console before Blender closes (I intentionally removed the file path):
```
Message: 'Checking all bpy.data.images\' derivatives as part of a load_post handler (bpy.data.filepath="C:\\Users\\***\Bench_01.blend")...'
Arguments: ()
Successfully applied 'Rename Asset' to assets : [bpy.data.collections['Bench_01']]

C:\Program Files\Blender Foundation\Blender 3.6>
```

**Comment by rndllcprn** [comment]
Update: Seems this is happening to _some_ files that were originally created pre-Blender 2.80. Resorted in just having to rename the collection name for each affected file but still don't know what causes the crashing.

**Comment by Gorgious56** [comment]
Hello ! Honestly hard to tell, would you be able to share a file where this problem is present ?
