### ISSUE TITLE
No "show custom properties" in addon preference

### ISSUE THREAD

**Issue by beetaa** [Gorgious56/asset_browser_utilities#141]
as is described in README:

![image](https://github.com/Gorgious56/asset_browser_utilities/assets/5688224/b81de16a-aa95-4422-af9d-bb606279762a)

but there is no entry in blender addon preference.

**Comment by Gorgious56** [comment]
Hello, I need to update the Readme. I removed the feature because there is really no point in having custom properties for asset meta data. You can't access them from other files so I suggest you either use custom props on the asset itself or use the tag system. Cheers
