### ISSUE TITLE
4.1.1 The Asset Browser cannot filter by selection in Asset Browser

### ISSUE THREAD

**Issue by LiJT** [Gorgious56/asset_browser_utilities#143]
![PixPin_2024-06-07_23-38-52](https://github.com/Gorgious56/asset_browser_utilities/assets/11270197/68fa21a1-4a65-4bc3-9056-0745ed4d3563)

It seems the Asset browser can no longer have a selected status for material? So the addon cannot know which material is being selected? Please check the Gif above

**Comment by Gorgious56** [comment]
Hello, thanks for the report ! This should be fixed with https://github.com/Gorgious56/asset_browser_utilities/commit/a541f739ae2c6cdc95dae7e89a6c73288d7c5fb3

Cheers

**Comment by LiJT** [comment]
hey @Gorgious56 thank you so much for the fast update!
