### ISSUE TITLE
4.1.1 Cannot Create new Custome Operation Preset in Preference

### ISSUE THREAD

**Issue by LiJT** [Gorgious56/asset_browser_utilities#144]
![PixPin_2024-06-10_11-18-01](https://github.com/Gorgious56/asset_browser_utilities/assets/11270197/f2c63c8f-0a41-49e4-b72c-b519d91c987d)

> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\startup\bl_ui\space_userpref.py", line 2175, in draw_addon_preferences
>     draw(context)
>   File "C:\Users\charl\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\asset_browser_utilities\core\preferences\ui.py", line 43, in draw
>     preset.draw(layout, context, header="Expand", rename=True)
>   File "C:\Users\charl\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\asset_browser_utilities\core\cache\prop.py", line 86, in draw
>     default_setting.draw(box, context)
>   File "C:\Users\charl\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\asset_browser_utilities\module\custom_operation\operator\operation_custom.py", line 42, in draw
>     operation_pg = self.operations[i]
>                    ~~~~~~~~~~~~~~~^^^
> IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

The error msges above are the one I got from Console command, I hope this helps.... I need a Preset to fast rename my stuff so bad so yeah if you feel free please fix it as you can haha

Thanks in advance!

**Comment by Gorgious56** [comment]
Hello, thanks again for the report. I've issued a fix, do tell me if it worked. The interface is a little awkward but you should be able to add the operation by clicking on the blue + icon.

Cheers

**Comment by LiJT** [comment]
> Hello, thanks again for the report. I've issued a fix, do tell me if it worked. The interface is a little awkward but you should be able to add the operation by clicking on the blue + icon.
> 
> Cheers

Thank you so much Gorgious! It works like a charm now! you fixed two problems in one days ahah very nice thanks again!
