### ISSUE TITLE
Add batch author and description 

### ISSUE THREAD

**Issue by Aeneas-Herodotus** [Gorgious56/asset_browser_utilities#25]
Could you add a way to batch input authors and descriptions?

**Comment by Gorgious56** [comment]
Sure, I'll work on it !

**Comment by Aeneas-Herodotus** [comment]
Thanks very much, will save a lot of time. Very useful addon!

**Comment by Gorgious56** [comment]
I'll setup a new release in the next few minutes and link it here. 

Cheers

**Comment by Gorgious56** [comment]
OK it was pretty straightforward to implement. 
The feature is now available in the latest release !

:)

https://github.com/Gorgious56/asset_browser_utilities/releases

Cheers

**Comment by Aeneas-Herodotus** [comment]
Fantastic! Thanks for the very quick response. I’ll be using it a lot!
