### ISSUE TITLE
Batch marking assets throwing error (version: 0.0.12)

### ISSUE THREAD

**Issue by edin45** [Gorgious56/asset_browser_utilities#36]
Sorry for reporting so many issues today. But when i try to Batch mark assets in the current file or an external library i get this error message:
![Untitled](https://user-images.githubusercontent.com/48309852/151373912-8e0f3f1a-f80e-4bbf-a835-15ba3ae4e521.jpg)

Thanks in advance!

**Comment by Gorgious56** [comment]
No problem, this is helping me :)

I'm currently working on a batch of bug fixes on main branch but I won't be able to publish them until this week-end, are you using the latest release (https://github.com/Gorgious56/asset_browser_utilities/releases/download/0.0.12/asset_browser_utilities_0.0.12.zip) or the code downloaded with the clone tool ?

**Comment by edin45** [comment]
Thanks! That worked! Awesome Plugin!

**Comment by Gorgious56** [comment]
If you don't mind I'll keep it open until the fix is commited, just so I don't forget about it ^^

Cheers
