### ISSUE TITLE
In blender 2.8 and 2.9

### ISSUE THREAD

**Issue by MuhammadXr** [Gorgious56/asset_browser_utilities#40]
![image](https://user-images.githubusercontent.com/61615295/156914986-88cf80a4-c429-4fc4-85ef-f0f7fab27d92.png)

https://github.com/Gorgious56/asset_browser_utilities/releases

**Comment by Gorgious56** [comment]
Hello ! The asset browser editor is only available in version 3.0 and up so it's not compatible with previous versions, sorry.

**Comment by MuhammadXr** [comment]
Yes I understand thank you.
I am writing a batch import code.
But I'm not sure how to open the subfolders and import fbx from them.
can you explain to me a little bit
How to import FBX from all subfolders.
And the fbx name with the file name

**Comment by MuhammadXr** [comment]
I found a section in your code that checked this subfolder but did not understand its structure
