### ISSUE TITLE
Smart Tags

### ISSUE THREAD

**Issue by Gorgious56** [Gorgious56/asset_browser_utilities#47]
Add an option to setup smart tags. EG : add a tag to objects from one of their properties like scale, location, rotation, or custom properties, object color, etc.

- [x] Dimensions
- [x] Tricount (rounded up or down) & Vertcount
- [x] ID Custom property (user input)
- [x] Scale

**Comment by Intuos5** [comment]
I am also noting, in case these are doable: 
- Polycount (perhaps rounded down by increments of 250, 500, 1k, 5k, 10k, 50k, 100k, 250k, 500k, 750k, 1000k) 
- Filesize
- Object size (dimensions in the N-panel)  
![afbeelding](https://user-images.githubusercontent.com/63149655/164409869-856c3a7b-d7ff-496c-b1f7-982df17580b2.png)

**Comment by Gorgious56** [comment]
@Intuos5 
Funny I actually posted a snippet on the blender chat yesterday.
`[o.asset_data.tags.new("<" + str(math.ceil(sum(len(polygon.vertices) - 2 for polygon in o.data.polygons) / 500) * 500) + " Tris", skip_if_exists=True) for o in bpy.data.objects if o.type == "MESH" and o.asset_data is not None]`

This is doable. I just have to think a bit about how to make a system that is extendable enough to cover edge cases, but I don't think it will be to hard.

For the file size it would only work for assets that are contained individually in blend files since I never found a way to get the actual size on disk of assets with the python API.

**Comment by Gorgious56** [comment]
@Intuos5 I've started implementing this. How would you see the dimensions being applied to a tag ? Something like `X(0,621), Y(0,477), Z(0,411)` ? I'd be glad to hear your input on this. Cheers

**Comment by Intuos5** [comment]
@Gorgious56 I think that's a good format, I agree. I would personally add the units, so `X(0,621m), Y(0,477m), Z(0,411m)`. I don't need any unit conversion to be honest, meters would be fine by me.

**Comment by Gorgious56** [comment]
I abandoned file size because it's really hard to get in the end.
