### ISSUE TITLE
Extend custom operations

### ISSUE THREAD

**Issue by Gorgious56** [Gorgious56/asset_browser_utilities#51]
Following #44 :

- [x] Add an option to chain custom operations
- [x] Add additional custom operations:
    - [x] Rename (options : prefix, replace, suffix)
        - [x] Rename asset
        - [x] Rename data
        - [x] Rename material
    - [x] Transform
    - [x] Translate
    - [x] Rotate
    - [x] Scale
    - [x] Decimate (w/ target polygons)

**Comment by Intuos5** [comment]
I was thinking, for scene management, it would be great if we could rename material and mesh data by adding the object's name as prefix to both. That way, the risk of adding objects that share the same material/ mesh name is reduced when re-using existing data.

For instance, if you have assets such as this one:
![image](https://user-images.githubusercontent.com/63149655/165053471-4a4d9e76-7a11-45a6-b296-d350939d4366.png)
It becomes a chore to recall which material is applied to which object. In this situation, if you append the object's name as prefix, the names are no longer generic. 

So I asked around for a procedure to do this:

`for i, obj in enumerate(bpy.data.objects):
    s = next(gen)
    name = obj.name[: -4]
    obj.name = f"{name}{s}"
    obj.data.name = obj.name
    if obj.material_slots[0].material:
        mat_name = obj.material_slots[0].material.name
        obj.material_slots[0].material.name = f"{obj.name}_{mat_name}{s}"
    if obj.material_slots[1].material:
        mat_name = obj.material_slots[1].material.name
        obj.material_slots[1].material.name = f"{obj.name}_{mat_name}{s}"

I made some small edits to the code, but I am a complete novice in this, but I hope this could be of help. I don't know how many slots are needed, but let's say around 10 to be safe?

**Comment by Gorgious56** [comment]
@Intuos5 interesting, it could be doable, I see it like so.

- Rename
    - Data as asset name
        - Prefix 
        - Replace
        - Suffix
    - Material as asset name
        - Prefix 
        - Replace
        - Suffix

It does have an immediate problem though, that 
1. One piece of data can be shared by several assets (Two objects can share the same mesh)
2. One material can be shared by multiple asset

It wouldn't throw any error or anything, but it would just be overwritten by the latest asset that's been operated on.

We're bordering on the limits of the scope of the features of this addon though so it might not suit your exact needs unfortunately since I want to keep it relatively open-ended. I can help you personally nonetheless on some scripts if you need though. It just probably won't be supported by this addon.

also FYI this

```
    if obj.material_slots[0].material:
        mat_name = obj.material_slots[0].material.name
        obj.material_slots[0].material.name = f"{obj.name}_{mat_name}{s}"
    if obj.material_slots[1].material:
        mat_name = obj.material_slots[1].material.name
        obj.material_slots[1].material.name = f"{obj.name}_{mat_name}{s}"
```

can be replaced (and expanded to work on any number of slots) by this
```
for slot in obj.material_slots:
    if slot.material:
        mat_name = slot.material.name
        slot.material.name = f"{obj.name}_{mat_name}{s}"
```

**Comment by Intuos5** [comment]
I understand that completely, I'm all for an open-ended addon too!
I agree with your renaming options. In the interface, you can see whether a material has multiple users (when the material or mesh is used by multiple assets). One way to circumvent renaming these would be to add a check for single use. If a datablock is used by multiple assets, print the name to the console and do not process. I think that's the failsafe method. If users do want the material/ mesh data to be renamed, it should be made unique first. Or, the other way around, it should, if possible, prompt a warning to continue and make unique. But I don't think the latter is required really. I can only imagine such batch operations for third party assets tbh. That's where my need came from anyways.
