### ISSUE TITLE
3.2 Beta - ModuleNotFoundError

### ISSUE THREAD

**Issue by ndrwstn** [Gorgious56/asset_browser_utilities#65]
![Screen Shot 2022-06-03 at 10 47 38 PM](https://user-images.githubusercontent.com/10574509/171976264-06fc2a77-c464-4909-9cc9-364492bc0aff.png)

I'm not able to enable this module on Blender 3.2.0 Beta. It seems to correctly install but states no module found. I don't believe this is related to the pinned issue #35, but I've been wrong before.

**Comment by Gorgious56** [comment]
Hello ! This is strange, what version did you download ?

**Comment by ndrwstn** [comment]
Sorry, that was a pretty poor issue report:

Installing the latest release (0.2.1) here, which downloads as "asset_utilities_browser.zip" to Blender 3.2 Beta on a MBP16  running macOS 12.3.1. When the add-on is installed via the Add-ons "Install" button from downloads, I can't enable the add-on.

If I go into my "~/Application Support/Blender/3.2/scripts/addons/"folder and rename the  "asset_browser_utilities-0.2.1" folder to "asset_browser_utilities" and refresh it seems to enable fine.

**Comment by Gorgious56** [comment]
That might be a MacOS specific thing unfortunately, on my end the folder is copied without the versioning numbers. 

I think I can solve it by not adding the version number to the release zip file, since that's just a convenience thing and the addon number is found int the `__init__.py` file at the root of the addon anyways.

Thanks for the report ! I'll see what I an do for the next release. Cheers

**Comment by Gorgious56** [comment]
I've pushed a new release without the version numbering. Feel free to test and tell me if it solves the problem without having to mess with the folder name

**Comment by Gorgious56** [comment]
I'm closing this since no additional information. Feel free to reopen if the problem persists.

**Comment by KelvinLaw-jpg** [comment]
Just experienced the same problem, for windows user, you will need to go to your "C:\Users\ {YOUR OWN USER NAME} \AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons" and rename the file name to "asset_browser_utilities"
